### ISSUE TITLE
fix vulnerability

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/squash#110]
- Delete package-lock.json
- Run `npm install`
- Commit package-lock.json
- Create pull request

**Comment by jugalj05hi** [comment]
Hi, I would like to take up this issue. Thank you.

**Comment by arshadkazmi42** [comment]
sure. go ahead

**Comment by jugalj05hi** [comment]
Thank you for the opportunity. I'd like to do some more contributions if you don't mind.
