### ISSUE TITLE
Change tests to run on pull request - github workflow

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/squash#120]
Change this line

https://github.com/arshadkazmi42/squash/blob/master/.github/workflows/nodejs.yml#L3

similar to these lines

https://github.com/gh-conf/rhof/blob/master/.github/workflows/nodejs.yml#L3-L5

**Comment by biohazard2117** [comment]
Assign it to me I will be able to do it

**Comment by arshadkazmi42** [comment]
Assigned
