### ISSUE TITLE
[Suggestion] Pass args to command

### ISSUE THREAD

**Issue by ArthurCueio** [arshadkazmi42/squash#46]
This could be done by adding `"$@"` after the command in the sh file.

**Comment by arshadkazmi42** [comment]
It's a really good suggestion. Would you like to send a PR for this?

**Comment by ArthurCueio** [comment]
Yes, I'll submit one soon. :+1:

**Comment by ArthurCueio** [comment]
Hey @arshadkazmi42, An example:

If you create an alias `commit` for `git commit`:
`$ commit -m My commit
// Command "git commit" is called`

If you add "$@" after the command in the sh file:
`$ commit -m My commit
// Command "git commit -m My commit" is called`

**Comment by arshadkazmi42** [comment]
That makes sense, it will be better to include this in the library. But we would not want it for everything, we should have some flag while createing alias, to enable it.

**Comment by ArthurCueio** [comment]
I think it will be better to split this into 2 PRs:
1. Adapt `Util.parserInput()` to handle multiple flags.
2. Add the `--pass-args` flag.

I would be happy to implement both.
