### ISSUE TITLE
Error removing squashed command

### ISSUE THREAD

**Issue by Zandew** [arshadkazmi42/squash#64]
I'm trying to remove a squashed command, but it displays this error.
![screenshot from 2019-02-13 22-00-03](https://user-images.githubusercontent.com/39287272/52759718-ef8ecd00-2fda-11e9-8597-55cf40ec6a9a.png)
Also should update readme to say --rm= instead of just --rm? had to look around for a while to find this.

**Comment by arshadkazmi42** [comment]
You might not have given a command name which you want to remove.
`squash --list`
this will give you list of commands
`squash --rm={{commad_name}}`
in above command, command_name is the name of any command from squash list

**Comment by Zandew** [comment]
Alright it worked, thanks

**Comment by arshadkazmi42** [comment]
Would you like to send a PR for updating README?

**Comment by Zandew** [comment]
sure I'll work on one
