### ISSUE TITLE
Usage demo for all flags

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/squash#66]
Let's create some gifs to showcase demo of using all types of flags in squash
- [x] alias #78
- [x] list #103 
- [x] system-alias #103 
- [x] rm #103 
- [x] help #103 
- [x] pass-args #103 
- [x] version #103

**Comment by co16353sidak** [comment]
Happy to work on this @arshadkazmi42 please assign this to me if possible

**Comment by arshadkazmi42** [comment]
Go ahead. Create a PR

**Comment by co16353sidak** [comment]
Let me create a few samples and send it your way 👍

**Comment by arshadkazmi42** [comment]
@co16353sidak Are you still working on this? As I was planning on working on this if you are busy with something else.

**Comment by co16353sidak** [comment]
We could both work on this together, we can divide the flags amongs each other.

Plus a sample from your end would help me understand how you want the gifs.

**Comment by arshadkazmi42** [comment]
Cool. I will add one example and you create gifs based on that

**Comment by co16353sidak** [comment]
Also please do inform me on the appropriate software to use for this, because I would want to ensure consistency with your example.

**Comment by arshadkazmi42** [comment]
@co16353sidak I have added example for `alias` flag at #78 
I use [peek](https://github.com/phw/peek) for creating screen recorded gifs.

**Comment by co16353sidak** [comment]
> I use [peek](https://github.com/phw/peek) for creating screen recorded gifs.

I guess peek is not available for Mac, I will find a suitable alternative.

**Comment by co16353sidak** [comment]
Added a few more gifs, please review @arshadkazmi42
