### ISSUE TITLE
Creating an alias throws mkdir fault

### ISSUE THREAD

**Issue by co16353sidak** [arshadkazmi42/squash#67]
Installing squash by following the given steps in the tutorial, 
when I try to add an alias for a command it throws an error, linking the screenshot below.

<img width="775" alt="screenshot 2019-02-14 at 2 33 15 pm" src="https://user-images.githubusercontent.com/35738138/52777785-9c645b00-306a-11e9-99a9-cf73b581f2e3.png">

it tries to create a `local/.squash` file but finds it already there.
Is this error specific to my system or something which could be fixed.

OS: MacOS 10.14.3

**Comment by arshadkazmi42** [comment]
Can you also share which version of node and npm are you using?

**Comment by co16353sidak** [comment]
@arshadkazmi42 
Latest I hope.

<img width="408" alt="screenshot 2019-02-14 at 3 19 19 pm" src="https://user-images.githubusercontent.com/35738138/52778399-f44f9180-306b-11e9-854c-6fed220a46d1.png">

**Comment by arshadkazmi42** [comment]
Are you getting this error every time you are squashing a command?

You should add your command inside double quotes if it contains spaces
`sudo squash "diskutil list" --alias=diskking`

**Comment by co16353sidak** [comment]
1. Yes.
<img width="766" alt="screenshot 2019-02-14 at 3 22 23 pm" src="https://user-images.githubusercontent.com/35738138/52778584-55776500-306c-11e9-8fea-d2b242cb2e26.png">


> You should add your command inside double quotes if it contains spaces
> `sudo squash "diskutil list" --alias=diskking`
2. Got it.

**Comment by arshadkazmi42** [comment]
I just tried it in another laptop. I can reproduce it, looks like some issue in create directory logic.

**Comment by co16353sidak** [comment]
@arshadkazmi42 Would like to work in this with you if possible. Is there any way this could be possible

**Comment by arshadkazmi42** [comment]
@co16353sidak Sure.
You can send a PR for this if you like.
The issue is somewhere here

https://github.com/arshadkazmi42/squash/blob/master/lib/file-operations/command-create.js#L12
https://github.com/arshadkazmi42/squash/blob/master/lib/squash.js#L35

Create directory is getting called twice.
We can remove createDirectory from command-create.js file.
as its handled in squash.js
I think this should fix this issue.

**Comment by co16353sidak** [comment]
Please check.
