### ISSUE TITLE
Remove dummy squashed commands 

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/squash#75]
While running tests, some dummy commands are generated and stored in the config.
Let's modify the tests to remove those dummy squashed commands once all tests are completed

**Comment by Zandew** [comment]
In the Tests folder, I do not see --alias being tested, could you direct me to where these dummy commands are being created?

**Comment by ArthurCueio** [comment]
> In the Tests folder, I do not see --alias being tested, could you direct me to where these dummy commands are being created?

They are created in the `tests/local.js` file.

We really should change this name now that TravisCI can run this test. It's going to avoid confusion in the future.

**Comment by arshadkazmi42** [comment]
@ArthurCueio Thanks for pointing @Zandew to right direction

> We really should change this name now that TravisCI can run this test. It's going to avoid confusion in the future.

This is actually right, let's move all the tests to `test/test.js` file.
I will create a separate issue for that

**Comment by arshadkazmi42** [comment]
Create an issue for this #77

**Comment by ArthurCueio** [comment]
PING @Zandew . Are you still working on this?
