### ISSUE TITLE
Release 1.2.3 on NPM

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/squash#76]
All the below issues needs to be fixed for this release
- [ ] #66  (Moved to #88 )
- [x] #75 
- [x] #77

**Comment by ArthurCueio** [comment]
Hey @arshadkazmi42 we can remove #66 from this list. It doesn't affect the functionality of the software in any way. 1.2.3 is good to go from the current master branch.

**Comment by arshadkazmi42** [comment]
@ArthurCueio Yes, right. Let me move that to a separate issue and let's release 1.2.3

**Comment by arshadkazmi42** [comment]
@ArthurCueio Deployed 1.2.3
https://www.npmjs.com/package/ak-squash
