### ISSUE TITLE
Update contributors hof

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/squash#83]
Replace Contributors information in README with the below code

`<a href="https://github.com/arshadkazmi42"><img src="https://github.com/arshadkazmi42.png" width="30" /></a><a href="https://github.com/ArthurCueio"><img src="https://github.com/ArthurCueio.png" width="30" /></a><a href="https://github.com/Zandew"><img src="https://github.com/Zandew.png" width="30" /></a><a href="https://github.com/co16353sidak"><img src="https://github.com/co16353sidak.png" width="30" /></a><a href="https://github.com/samuelweekes"><img src="https://github.com/samuelweekes.png" width="30" /></a><a href="https://github.com/alexmarginean16"><img src="https://github.com/alexmarginean16.png" width="30" /></a><a href="https://github.com/Aneal-Sharma"><img src="https://github.com/Aneal-Sharma.png" width="30" /></a><a href="https://github.com/konstunn"><img src="https://github.com/konstunn.png" width="30" /></a><a href="https://github.com/mzmmlds"><img src="https://github.com/mzmmlds.png" width="30" /></a><a href="https://github.com/fathurifki"><img src="https://github.com/fathurifki.png" width="30" /></a>`

**Comment by jsmiith** [comment]
Got it.
