### ISSUE TITLE
Change root dir for aliases

### ISSUE THREAD

**Issue by ArthurCueio** [arshadkazmi42/squash#85]
The current `/usr/local/.squash` folder requires root privileges. Forcing the user to run squash as root (`sudo`). Alternatively we could use:

- `~/.local/bin`
or 
- `~/bin`

Both of these won't need root permissions in order to create/delete files. Some side effects would be:

- No need to manually export $PATH as both of the above paths are alredy exported by default.
- The user wouldn't have to run squash as root. (Changes in #74 can be reverted after this)
- Squashed commands would become user-wide instead of the current system-wide.

To change this all we need is change the following line:

https://github.com/arshadkazmi42/squash/blob/4571d35423c4614d35d07bd830478fc8571d00e8/lib/util/constants.js#L9

**Comment by arshadkazmi42** [comment]
@ArthurCueio this is a really good idea. this will make it really easy to use it.
Would you like to send a PR for this?
