### ISSUE TITLE
Add a valid license

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/squash#91]
Right now squash is Unlicesnsed.
I think we should add MIT license to this.

**Comment by arshadkazmi42** [comment]
@ArthurCueio Any thoughts on this?

**Comment by ArthurCueio** [comment]
I agree the MIT license would be best. We also have to update it on `package.json`

**Comment by arshadkazmi42** [comment]
Yes. I will send a PR for this. We can push this with our 1.2.4 release.
