### ISSUE TITLE
Rewrite list command

### ISSUE THREAD

**Issue by ArthurCueio** [arshadkazmi42/squash#96]
We need a better way to keep track squashed commands. In order to change the root dir to a place we don't need to manually export (#85). The current version will try to list all files inside the squash directory.

This PR should be made against the `2.0 dev` branch

**Comment by arshadkazmi42** [comment]
@ArthurCueio I was thinking with this change, all existing squashed commands will break with list flags, so should add something for migration of the old commands or any handlers? Any thoughts?

**Comment by ArthurCueio** [comment]
When #86 is merged I'll start working on a standalone script to migrate the old commands to this new format.
